var Settings = {};
Settings.ease                     = Power2.easeInOut;
Settings.fade_up_delay            = 0.125;
Settings.fade_down_delay          = Settings.fade_up_delay;
Settings.fade_up_duration         = 0.25;
Settings.fade_down_duration       = Settings.fade_up_duration;
Settings.focus_duration           = 0.25;
Settings.legal_duration           = 0.5;
Settings.legal_delay              = 0.25;
Settings.wipe_open_delay          = 0;
Settings.wipe_closed_delay        = 2;
Settings.expand_collapse_duration = 0.25;
Settings.scroll_content_duration  = 0.25;
Settings.card_padding             = 20;
Settings.hidden_scale             = 0.85;
Settings.shim_animation_duration  = 0.45;
Settings.card_animation_duration  = 0.5;
Settings.sidebar_percent_of_stage = 0.25;
Settings.card_padding             = 40;

export default Settings;