// this file auto-generated by gulp `compile-templates` task.. do not edit!

// need the handlebars runtime for partials
// https://github.com/epeli/node-hbsfy/blob/master/example/index.js
var Handlebars = require("hbsfy/runtime");

// begin templates object
var templates = {};

templates["partials/order/templates/deviceList"] = require('./templates/deviceList.jsp');
Handlebars.registerPartial('partials/order/templates/deviceList', templates["partials/order/templates/deviceList"]);

templates["partials/order/templates/legalCard"] = require('./templates/legalCard.jsp');
Handlebars.registerPartial('partials/order/templates/legalCard', templates["partials/order/templates/legalCard"]);

templates["partials/order/templates/partnerList"] = require('./templates/partnerList.jsp');
Handlebars.registerPartial('partials/order/templates/partnerList', templates["partials/order/templates/partnerList"]);

templates["partials/order/templates/partnerLogos"] = require('./templates/partnerLogos.jsp');
Handlebars.registerPartial('partials/order/templates/partnerLogos', templates["partials/order/templates/partnerLogos"]);

templates["partials/order/templates/partnerLogosSmartTVs"] = require('./templates/partnerLogosSmartTVs.jsp');
Handlebars.registerPartial('partials/order/templates/partnerLogosSmartTVs', templates["partials/order/templates/partnerLogosSmartTVs"]);

templates["partials/order/templates/picker"] = require('./templates/picker.jsp');
Handlebars.registerPartial('partials/order/templates/picker', templates["partials/order/templates/picker"]);

templates["partials/order/templates/providers_0"] = require('./templates/providers/0.jsp');
Handlebars.registerPartial('partials/order/templates/providers_0', templates["partials/order/templates/providers_0"]);

templates["partials/order/templates/providers_100"] = require('./templates/providers/100.jsp');
Handlebars.registerPartial('partials/order/templates/providers_100', templates["partials/order/templates/providers_100"]);

templates["partials/order/templates/providers_100_themes_8077000136"] = require('./templates/providers/100/themes/8077000136.jsp');
Handlebars.registerPartial('partials/order/templates/providers_100_themes_8077000136', templates["partials/order/templates/providers_100_themes_8077000136"]);

templates["partials/order/templates/providers_100_themes_8078510864"] = require('./templates/providers/100/themes/8078510864.jsp');
Handlebars.registerPartial('partials/order/templates/providers_100_themes_8078510864', templates["partials/order/templates/providers_100_themes_8078510864"]);

templates["partials/order/templates/providers_100_themes_8173424711"] = require('./templates/providers/100/themes/8173424711.jsp');
Handlebars.registerPartial('partials/order/templates/providers_100_themes_8173424711', templates["partials/order/templates/providers_100_themes_8173424711"]);

templates["partials/order/templates/providers_888888"] = require('./templates/providers/888888.jsp');
Handlebars.registerPartial('partials/order/templates/providers_888888', templates["partials/order/templates/providers_888888"]);

templates["partials/order/templates/providers_888888_themes_8077000136"] = require('./templates/providers/888888/themes/8077000136.jsp');
Handlebars.registerPartial('partials/order/templates/providers_888888_themes_8077000136', templates["partials/order/templates/providers_888888_themes_8077000136"]);

templates["partials/order/templates/providers_888888_themes_8078510864"] = require('./templates/providers/888888/themes/8078510864.jsp');
Handlebars.registerPartial('partials/order/templates/providers_888888_themes_8078510864', templates["partials/order/templates/providers_888888_themes_8078510864"]);

templates["partials/order/templates/providers_92"] = require('./templates/providers/92.jsp');
Handlebars.registerPartial('partials/order/templates/providers_92', templates["partials/order/templates/providers_92"]);

templates["partials/order/templates/providers_92_themes_8077000136"] = require('./templates/providers/92/themes/8077000136.jsp');
Handlebars.registerPartial('partials/order/templates/providers_92_themes_8077000136', templates["partials/order/templates/providers_92_themes_8077000136"]);

templates["partials/order/templates/providers_92_themes_8078510864"] = require('./templates/providers/92/themes/8078510864.jsp');
Handlebars.registerPartial('partials/order/templates/providers_92_themes_8078510864', templates["partials/order/templates/providers_92_themes_8078510864"]);

templates["partials/order/templates/providers_92_themes_8173424711"] = require('./templates/providers/92/themes/8173424711.jsp');
Handlebars.registerPartial('partials/order/templates/providers_92_themes_8173424711', templates["partials/order/templates/providers_92_themes_8173424711"]);

templates["partials/order/templates/providers_93"] = require('./templates/providers/93.jsp');
Handlebars.registerPartial('partials/order/templates/providers_93', templates["partials/order/templates/providers_93"]);

templates["partials/order/templates/providers_93_themes_8077000136"] = require('./templates/providers/93/themes/8077000136.jsp');
Handlebars.registerPartial('partials/order/templates/providers_93_themes_8077000136', templates["partials/order/templates/providers_93_themes_8077000136"]);

templates["partials/order/templates/providers_93_themes_8078510864"] = require('./templates/providers/93/themes/8078510864.jsp');
Handlebars.registerPartial('partials/order/templates/providers_93_themes_8078510864', templates["partials/order/templates/providers_93_themes_8078510864"]);

templates["partials/order/templates/providers_93_themes_8173424711"] = require('./templates/providers/93/themes/8173424711.jsp');
Handlebars.registerPartial('partials/order/templates/providers_93_themes_8173424711', templates["partials/order/templates/providers_93_themes_8173424711"]);

templates["partials/order/templates/providers_94"] = require('./templates/providers/94.jsp');
Handlebars.registerPartial('partials/order/templates/providers_94', templates["partials/order/templates/providers_94"]);

templates["partials/order/templates/providers_94_themes_8077000136"] = require('./templates/providers/94/themes/8077000136.jsp');
Handlebars.registerPartial('partials/order/templates/providers_94_themes_8077000136', templates["partials/order/templates/providers_94_themes_8077000136"]);

templates["partials/order/templates/providers_94_themes_8078510864"] = require('./templates/providers/94/themes/8078510864.jsp');
Handlebars.registerPartial('partials/order/templates/providers_94_themes_8078510864', templates["partials/order/templates/providers_94_themes_8078510864"]);

templates["partials/order/templates/providers_94_themes_8173424711"] = require('./templates/providers/94/themes/8173424711.jsp');
Handlebars.registerPartial('partials/order/templates/providers_94_themes_8173424711', templates["partials/order/templates/providers_94_themes_8173424711"]);

templates["partials/order/templates/providers_95"] = require('./templates/providers/95.jsp');
Handlebars.registerPartial('partials/order/templates/providers_95', templates["partials/order/templates/providers_95"]);

templates["partials/order/templates/providers_95_themes_8077000136"] = require('./templates/providers/95/themes/8077000136.jsp');
Handlebars.registerPartial('partials/order/templates/providers_95_themes_8077000136', templates["partials/order/templates/providers_95_themes_8077000136"]);

templates["partials/order/templates/providers_95_themes_8078510864"] = require('./templates/providers/95/themes/8078510864.jsp');
Handlebars.registerPartial('partials/order/templates/providers_95_themes_8078510864', templates["partials/order/templates/providers_95_themes_8078510864"]);

templates["partials/order/templates/providers_95_themes_8173424711"] = require('./templates/providers/95/themes/8173424711.jsp');
Handlebars.registerPartial('partials/order/templates/providers_95_themes_8173424711', templates["partials/order/templates/providers_95_themes_8173424711"]);

templates["partials/order/templates/providers_98"] = require('./templates/providers/98.jsp');
Handlebars.registerPartial('partials/order/templates/providers_98', templates["partials/order/templates/providers_98"]);

templates["partials/order/templates/providers_98_themes_8077000136"] = require('./templates/providers/98/themes/8077000136.jsp');
Handlebars.registerPartial('partials/order/templates/providers_98_themes_8077000136', templates["partials/order/templates/providers_98_themes_8077000136"]);

templates["partials/order/templates/providers_98_themes_8078510864"] = require('./templates/providers/98/themes/8078510864.jsp');
Handlebars.registerPartial('partials/order/templates/providers_98_themes_8078510864', templates["partials/order/templates/providers_98_themes_8078510864"]);

templates["partials/order/templates/providers_98_themes_8173424711"] = require('./templates/providers/98/themes/8173424711.jsp');
Handlebars.registerPartial('partials/order/templates/providers_98_themes_8173424711', templates["partials/order/templates/providers_98_themes_8173424711"]);

templates["partials/order/templates/providers_99"] = require('./templates/providers/99.jsp');
Handlebars.registerPartial('partials/order/templates/providers_99', templates["partials/order/templates/providers_99"]);

templates["partials/order/templates/providers_99_themes_8077000136"] = require('./templates/providers/99/themes/8077000136.jsp');
Handlebars.registerPartial('partials/order/templates/providers_99_themes_8077000136', templates["partials/order/templates/providers_99_themes_8077000136"]);

templates["partials/order/templates/providers_99_themes_8078510864"] = require('./templates/providers/99/themes/8078510864.jsp');
Handlebars.registerPartial('partials/order/templates/providers_99_themes_8078510864', templates["partials/order/templates/providers_99_themes_8078510864"]);

templates["partials/order/templates/providers_99_themes_8173424711"] = require('./templates/providers/99/themes/8173424711.jsp');
Handlebars.registerPartial('partials/order/templates/providers_99_themes_8173424711', templates["partials/order/templates/providers_99_themes_8173424711"]);

templates["partials/order/templates/sidebar"] = require('./templates/sidebar.jsp');
Handlebars.registerPartial('partials/order/templates/sidebar', templates["partials/order/templates/sidebar"]);

templates["partials/order/templates/tray"] = require('./templates/tray.jsp');
Handlebars.registerPartial('partials/order/templates/tray', templates["partials/order/templates/tray"]);

export default templates;